sudo: required
dist: bionic

language: erlang

otp_release:
 - 22.3.4
 - 23.0.2

install: "true"

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3

script:
  - env
  - ./rebar3 compile
  - ./rebar3 xref
